{
 "title": "IoT Mi 米家插座",
 "tags": [ "zx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据来源", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "当前开关状态",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "IoT_Mi_plugin_alive{job=\"MiIoT\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "IoT_Mi_plugin_staus{job=\"MiIoT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "设备温度",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "IoT_Mi_plugin_temperature{job=\"MiIoT\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "当前功率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "IoT_Mi_plugin_watt{job=\"MiIoT\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}