{
 "title": "JMS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据来源", "query": "prometheus" },
   {
    "name": "jms_name",
    "label": "JMS 实例名",
    "query": {
     "query": "label_values(jms_total_bytes,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "总流量/重置日期",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jms_total_bytes{job=\"jms\", name=~\"$jms_name\"}",
     "legendFormat": "$jms_name"
    },
    {
     "expr": "jms_reset_day{job=\"jms\", name=~\"$jms_name\"}",
     "legendFormat": "$jms_name"
    }
   ]
  },
  {
   "title": "使用百分比",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jms_usage_bytes{job=\"jms\", name=~\"$jms_name\"}/jms_total_bytes{job=\"jms\", name=~\"$jms_name\"}",
     "legendFormat": "$jms_name"
    }
   ]
  },
  {
   "title": "流量使用情况",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jms_usage_bytes{job=\"jms\", name=~\"$jms_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}