{
 "title": "多机器聚合监控",
 "tags": [ "zx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据来源", "query": "prometheus" },
   {
    "name": "job",
    "label": "job类型",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "hostname",
    "label": "节点名",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},nodename)"
    }
   },
   {
    "name": "instance",
    "label": "instance节点",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "exported_job",
    "query": {
     "query": "label_values(gpu_nvidia_usage, exported_job)"
    }
   },
   {
    "name": "gpu_nvidia_mem",
    "query": {
     "query": "label_values(gpu_nvidia_usage, gpu_nvidia_mem)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "运行时信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU%",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", job=\"$job\"}[1m])) by(instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM%",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 ",
     "legendFormat": "{{instance}}-MEM"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "{{instance}}-SWAP"
    }
   ]
  },
  {
   "title": "MEM-SWAP总量",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\"}",
     "legendFormat": "{{instance}}-MEM"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"$job\"}",
     "legendFormat": "{{instance}}-SWAP"
    }
   ]
  },
  {
   "title": "GPU%",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "gpu_nvidia_usage{exported_job=\"$exported_job\"}",
     "legendFormat": "{{nodename}}-GPU"
    },
    {
     "expr": "(gpu_nvidia_memory_usage{exported_job=\"$exported_job\"} / gpu_nvidia_memory_total{exported_job=\"$exported_job\"}) * 100",
     "legendFormat": "{{nodename}}-MEM"
    }
   ]
  },
  {
   "title": "GPU功耗",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "gpu_nvidia_power_usage", "legendFormat": "{{nodename}}" }
   ]
  },
  {
   "title": "GPU-MEM总量-最大功耗",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_nvidia_memory_total", "legendFormat": "{{nodename}}-MEM" },
    { "expr": "gpu_nvidia_power_cap", "legendFormat": "{{nodename}}-W" }
   ]
  },
  {
   "title": "网络速率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total[$__rate_interval]))by(instance) * on(instance) group_left(nodename)(node_uname_info)",
     "legendFormat": "{{nodename}}-send"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total[$__rate_interval]))by(instance)  * on(instance) group_left(nodename)(node_uname_info)",
     "legendFormat": "{{nodename}}-recv"
    }
   ]
  },
  {
   "title": "流量使用总量",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_network_receive_bytes_total{job=\"node\"} + node_network_transmit_bytes_total{job=\"node\"})by(instance) * on(instance) group_left(nodename)(node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "磁盘读写速率",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_time_seconds_total[$__rate_interval]))by(instance) * on(instance) group_left(nodename)(node_uname_info)",
     "legendFormat": "{{nodename}}-R"
    },
    {
     "expr": "sum(irate(node_disk_write_time_seconds_total[$__rate_interval]))by(instance) * on(instance) group_left(nodename)(node_uname_info)",
     "legendFormat": "{{nodename}}-W"
    }
   ]
  },
  {
   "title": "磁盘使用情况",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node\", device=~\"/dev/(sd.*|vd.*|hd.*|nvme.*|mapper/.*)\"}"
    },
    {
     "expr": "node_filesystem_avail_bytes{job=\"node\", device=~\"/dev/(sd.*|vd.*|hd.*|nvme.*|mapper/.*)\"}"
    },
    { "expr": "node_uname_info" },
    {
     "expr": "(1 - (node_filesystem_avail_bytes{job=\"node\", device=~\"/dev/(sd.*|vd.*|hd.*|nvme.*|mapper/.*)\"} / node_filesystem_size_bytes{job=\"node\", device=~\"/dev/(sd.*|vd.*|hd.*|nvme.*|mapper/.*)\"}))*100"
    }
   ]
  }
 ]
}