{
 "title": "多机器聚合监控-v11",
 "description": "grafana v11.x 版本上的更新。",
 "tags": [ "zx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据来源", "query": "prometheus" },
   {
    "name": "job",
    "label": "job类型",
    "query": {
     "query": "label_values(node_uname_info{job=\"node\"},job)"
    }
   },
   {
    "name": "gpu_nvidia",
    "label": "pushgateway数据",
    "query": {
     "query": "label_values({exported_job=\"gpu_nvidia\"},exported_job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU/MEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU%",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", job=\"$job\"}[1m])) by(instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MEM-总量",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_uname_info{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SWAP总量",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_uname_info{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "repeat": "datasource" },
  {
   "title": "GPU%",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_nvidia_utilization{index=~\".*\"}",
     "legendFormat": "{{instance}} ID:{{index}}"
    }
   ]
  },
  {
   "title": "GPU MEM%",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(gpu_nvidia_memory_used / gpu_nvidia_memory_total) * 100",
     "legendFormat": "{{instance}} ID:{{index}}"
    }
   ]
  },
  {
   "title": "GPU MEM总量",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    { "expr": "gpu_nvidia_memory_total", "legendFormat": "__auto" },
    { "expr": "gpu_nvidia_memory_reserved", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "功耗",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "gpu_nvidia_power_usage", "legendFormat": "{{instance}} ID:{{index}}" }
   ]
  },
  {
   "title": "GPU 功率最大值",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "gpu_nvidia_pwoer_limit", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "网络/IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "网络速率",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=\"$job\"}[$__rate_interval]) + irate(node_network_transmit_bytes_total{job=\"$job\"}[$__rate_interval])) by(instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "流量使用量",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_network_receive_bytes_total{job=\"$job\"} + node_network_transmit_bytes_total{job=\"$job\"}) by(instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "硬盘IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "硬盘IO",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(node_disk_read_time_seconds_total[$__rate_interval]) + irate(node_disk_write_time_seconds_total[$__rate_interval]))by(instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "硬盘使用情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "磁盘使用情况",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=\"$job\", device=~\"/dev/(sd.*|vd.*|hd.*|nvme.*|mapper/.*)\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "node_filesystem_avail_bytes{job=\"$job\", device=~\"/dev/(sd.*|vd.*|hd.*|nvme.*|mapper/.*)\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "(1 - (node_filesystem_avail_bytes{job=\"$job\", device=~\"/dev/(sd.*|vd.*|hd.*|nvme.*|mapper/.*)\"} / node_filesystem_size_bytes{job=\"$job\", device=~\"/dev/(sd.*|vd.*|hd.*|nvme.*|mapper/.*)\"}))*100",
       "legendFormat": "__auto"
      },
      { "expr": "node_uname_info", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}