#!/usr/bin/bash


CWD=$(cd $(dirname "$0");pwd)
cd $CWD

# 加载配置
source vm.conf
source log.sh

OBJECT="$1"
OPERATION="$2"


if [ "$OBJECT" = "$VM_NAME" ]; then
	case "$OPERATION" in
        "prepare")
			log "${VM_NAME} 启动前执行..."
			timeout 180s bash vfio-startup.sh
			log "${VM_NAME} 启动前执行... 结束"
			;;

        "release")
			log "${VM_NAME} 结束后执行..."
            timeout 180s bash vfio-down.sh
			log "${VM_NAME} 结束后执行... 结束"
            ;;
	esac
fi

